name: Hello World Pipeline

on:
  push:       # Déclenché quand tu pousses du code
    branches: [ "main" ]
  pull_request:   # Déclenché pour les PR vers main
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Lancer Hello World
        run: python hello.py
